In [198]:
import numpy as np
import random 
import matplotlib.pyplot as plt
%matplotlib inline

class LinearRegressionWithMultipleVariable(object):
    
    '''
    h(x) = θ_0 * x_0 + θ_1 * x_1 + θ_2 * x_2 + θ_3 * x_3 ... θ_n * x_n | x_0 = 1
    '''
    
    def __init__(self, vector_size, points):
        self.lr = 0.01
        self.vector_size = vector_size
        self.parameters = np.zeros((1, vector_size)).T
        self.points = points
        pass
    
    
    def predict(self, y):
        y = np.array(y, ndmin = 2).T
        print(y)
        print(self.parameters)
        predict = np.dot(self.points, self.parameters)
        print(predict)
        pass
    
    
    def train(self, y):
        y = np.array(y , ndmin=2).T
        predict = np.dot(self.points, self.parameters)
        error = (predict - y)**2
        print(error)
        print("process.....")
        epochs = 2000
        for i in range(epochs):
            grad_vector = np.zeros((1, self.vector_size)).T
            for ip, iy in zip(self.points, y):
                grad_vector += (np.dot(self.points, self.parameters) - y)
            print(grad_vector)
            self.parameters -= self.lr * grad_vector
        print(error)
        
        
        pass

In [199]:
points = np.array([[1, random.randint(1, 10), random.randint(1, 10), random.randint(1, 10)] for i in range(4)])
linreg = LinearRegressionWithMultipleVariable(4, points)
print(linreg.points)

[[ 1  5 10  6]
 [ 1  8  7  4]
 [ 1 10  3  2]
 [ 1  4  3  2]]


In [200]:
linreg.predict([5,4,7,4])

[[5]
 [4]
 [7]
 [4]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [201]:
linreg.train([5,4,7,4])

[[ 25.]
 [ 16.]
 [ 49.]
 [ 16.]]
process.....
[[-20.]
 [-16.]
 [-28.]
 [-16.]]
[[ -0.96]
 [  0.32]
 [-16.16]
 [ -8.  ]]
[[  7.3984]
 [  6.0608]
 [-13.6704]
 [ -5.4336]]
[[ 12.662528]
 [  8.522496]
 [-14.31552 ]
 [ -4.624128]]
[[ 17.2875264 ]
 [ 10.03700224]
 [-16.14322688]
 [ -4.40643584]]
[[ 22.10346025]
 [ 11.35879373]
 [-18.55982674]
 [ -4.41415516]]
[[ 27.43089103]
 [ 12.74285764]
 [-21.40717102]
 [ -4.53538895]]
[[ 33.43644561]
 [ 14.28757767]
 [-24.66985808]
 [ -4.73979017]]
[[ 40.24696513]
 [ 16.04402168]
 [-28.38278079]
 [ -5.02369424]]
[[ 47.98708112]
 [ 18.05102584]
 [-32.60243883]
 [ -5.39278708]]
[[ 56.79263714]
 [ 20.34674313]
 [-37.39861678]
 [ -5.85671883]]
[[ 66.81664226]
 [ 22.97276755]
 [-42.852648  ]
 [ -6.4275317 ]]
[[ 78.23308987]
 [ 25.97596276]
 [-49.05790042]
 [ -7.1193199 ]]
[[ 91.24037066]
 [ 29.40963438]
 [-56.12111547]
 [ -7.9483039 ]]
[[ 106.06486808]
 [  33.33457751]
 [ -64.16418588]
 [  -8.93306206]]
[[ 122.9649671 ]
 [  37.82017996]
 [ -73.32626434]
 [ -

 [ -9.68857568e+08]]
[[  1.33357862e+10]
 [  3.58479327e+09]
 [ -7.18266840e+09]
 [ -1.10603164e+09]]
[[  1.52239111e+10]
 [  4.09234019e+09]
 [ -8.19961442e+09]
 [ -1.26262727e+09]]
[[  1.73793629e+10]
 [  4.67174729e+09]
 [ -9.36054303e+09]
 [ -1.44139423e+09]]
[[  1.98399908e+10]
 [  5.33318876e+09]
 [ -1.06858398e+10]
 [ -1.64547161e+09]]
[[  2.26490025e+10]
 [  6.08827932e+09]
 [ -1.21987764e+10]
 [ -1.87844295e+09]]
[[  2.58557234e+10]
 [  6.95027810e+09]
 [ -1.39259196e+10]
 [ -2.14439913e+09]]
[[  2.95164625e+10]
 [  7.93432152e+09]
 [ -1.58975975e+10]
 [ -2.44801028e+09]]
[[  3.36955011e+10]
 [  9.05768908e+09]
 [ -1.81484321e+10]
 [ -2.79460770e+09]]
[[  3.84662219e+10]
 [  1.03401067e+10]
 [ -2.07179473e+10]
 [ -3.19027753e+09]]
[[  4.39123972e+10]
 [  1.18040934e+10]
 [ -2.36512630e+10]
 [ -3.64196761e+09]]
[[  5.01296601e+10]
 [  1.34753561e+10]
 [ -2.69998873e+10]
 [ -4.15760947e+09]]
[[  5.72271837e+10]
 [  1.53832417e+10]
 [ -3.08226209e+10]
 [ -4.74625761e+09]]
[[  6.5

[[  2.63982902e+97]
 [  7.09612551e+96]
 [ -1.42181467e+97]
 [ -2.18939809e+96]]
[[  3.01358477e+97]
 [  8.10081849e+96]
 [ -1.62311990e+97]
 [ -2.49938034e+96]]
[[  3.44025810e+97]
 [  9.24775925e+96]
 [ -1.85292660e+97]
 [ -2.85325089e+96]]
[[  3.92734125e+97]
 [  1.05570877e+97]
 [ -2.11527010e+97]
 [ -3.25722362e+96]]
[[  4.48338726e+97]
 [  1.20517952e+97]
 [ -2.41475705e+97]
 [ -3.71839214e+96]]
[[  5.11816009e+97]
 [  1.37581283e+97]
 [ -2.75664637e+97]
 [ -4.24485444e+96]]
[[  5.84280618e+97]
 [  1.57060497e+97]
 [ -3.14694150e+97]
 [ -4.84585501e+96]]
[[  6.67005006e+97]
 [  1.79297644e+97]
 [ -3.59249592e+97]
 [ -5.53194724e+96]]
[[  7.61441787e+97]
 [  2.04683199e+97]
 [ -4.10113341e+97]
 [ -6.31517867e+96]]
[[  8.69249241e+97]
 [  2.33662925e+97]
 [ -4.68178548e+97]
 [ -7.20930262e+96]]
[[  9.92320432e+97]
 [  2.66745697e+97]
 [ -5.34464820e+97]
 [ -8.23001960e+96]]
[[  1.13281645e+98]
 [  3.04512438e+97]
 [ -6.10136122e+97]
 [ -9.39525307e+96]]
[[  1.29320436e+98]
 [  3.47

In [203]:
linreg.parameters

array([[ -1.35850399e+115],
       [ -3.65179515e+114],
       [  7.31691667e+114],
       [  1.12670405e+114]])

In [204]:
linreg.predict([5,4,7,4])

[[5]
 [4]
 [7]
 [4]]
[[ -1.35850399e+115]
 [ -3.65179515e+114]
 [  7.31691667e+114]
 [  1.12670405e+114]]
[[  4.80853753e+115]
 [  1.29258318e+115]
 [ -2.58988333e+115]
 [ -3.98806241e+114]]
